"""Add new parameter to Dog

Revision ID: 67807ba4460c
Revises: e34128e32120
Create Date: 2024-11-29 16:44:17.732953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67807ba4460c'
down_revision: Union[str, None] = 'e34128e32120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adopted_dogs', sa.Column('id_chip', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_adopted_dogs_id_chip'), 'adopted_dogs', ['id_chip'], unique=False)
    op.add_column('adoption_dogs', sa.Column('id_chip', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_adoption_dogs_id_chip'), 'adoption_dogs', ['id_chip'], unique=False)
    op.add_column('static_dogs', sa.Column('id_chip', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_static_dogs_id_chip'), 'static_dogs', ['id_chip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_static_dogs_id_chip'), table_name='static_dogs')
    op.drop_column('static_dogs', 'id_chip')
    op.drop_index(op.f('ix_adoption_dogs_id_chip'), table_name='adoption_dogs')
    op.drop_column('adoption_dogs', 'id_chip')
    op.drop_index(op.f('ix_adopted_dogs_id_chip'), table_name='adopted_dogs')
    op.drop_column('adopted_dogs', 'id_chip')
    # ### end Alembic commands ###
