"""Add capacity to course

Revision ID: 90695aaf8b7c
Revises: e3770bd8aa22
Create Date: 2024-12-03 07:06:18.405957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '90695aaf8b7c'
down_revision: Union[str, None] = 'e3770bd8aa22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_id', table_name='course')
    op.drop_table('course')
    op.drop_index('ix_schedule_id', table_name='schedule')
    op.drop_table('schedule')
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('ADMIN', 'AUXILIAR'),
               nullable=False)
    op.drop_index('ix_user_role', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('ADMIN', 'AUXILIAR'),
               nullable=True)
    op.create_table('schedule',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('day', mysql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'), nullable=False),
    sa.Column('start_hour', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('end_hour', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('curso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['course.id'], name='schedule_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_schedule_id', 'schedule', ['id'], unique=False)
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_course_id', 'course', ['id'], unique=False)
    # ### end Alembic commands ###
