"""Adding new parameters to Dog

Revision ID: 9dee3fed84c6
Revises: a34c27876d7a
Create Date: 2024-11-26 23:06:30.400993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dee3fed84c6'
down_revision: Union[str, None] = 'a34c27876d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adopted_dogs', sa.Column('entry_date', sa.Date(), nullable=True))
    op.add_column('adopted_dogs', sa.Column('is_sterilized', sa.Boolean(), nullable=False))
    op.add_column('adopted_dogs', sa.Column('is_dewormed', sa.Boolean(), nullable=False))
    op.add_column('adopted_dogs', sa.Column('operation', sa.String(length=255), nullable=True))
    op.alter_column('adopted_dogs', 'adopted_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_adopted_dogs_adopted_date', table_name='adopted_dogs')
    op.add_column('adoption_dogs', sa.Column('entry_date', sa.Date(), nullable=True))
    op.add_column('adoption_dogs', sa.Column('is_sterilized', sa.Boolean(), nullable=False))
    op.add_column('adoption_dogs', sa.Column('is_dewormed', sa.Boolean(), nullable=False))
    op.add_column('adoption_dogs', sa.Column('operation', sa.String(length=255), nullable=True))
    op.add_column('static_dogs', sa.Column('entry_date', sa.Date(), nullable=True))
    op.add_column('static_dogs', sa.Column('is_sterilized', sa.Boolean(), nullable=False))
    op.add_column('static_dogs', sa.Column('is_dewormed', sa.Boolean(), nullable=False))
    op.add_column('static_dogs', sa.Column('operation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('static_dogs', 'operation')
    op.drop_column('static_dogs', 'is_dewormed')
    op.drop_column('static_dogs', 'is_sterilized')
    op.drop_column('static_dogs', 'entry_date')
    op.drop_column('adoption_dogs', 'operation')
    op.drop_column('adoption_dogs', 'is_dewormed')
    op.drop_column('adoption_dogs', 'is_sterilized')
    op.drop_column('adoption_dogs', 'entry_date')
    op.create_index('ix_adopted_dogs_adopted_date', 'adopted_dogs', ['adopted_date'], unique=False)
    op.alter_column('adopted_dogs', 'adopted_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('adopted_dogs', 'operation')
    op.drop_column('adopted_dogs', 'is_dewormed')
    op.drop_column('adopted_dogs', 'is_sterilized')
    op.drop_column('adopted_dogs', 'entry_date')
    # ### end Alembic commands ###
