"""update relationship beetween Token and User rev.2

Revision ID: a34c27876d7a
Revises: ee056f008f32
Create Date: 2024-11-25 09:58:54.449721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34c27876d7a'
down_revision: Union[str, None] = 'ee056f008f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_ibfk_1', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_ibfk_1', 'token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
