"""Adding new parameters to Dog

Revision ID: cc768f8e383a
Revises: 9dee3fed84c6
Create Date: 2024-11-27 00:19:35.920920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc768f8e383a'
down_revision: Union[str, None] = '9dee3fed84c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
