"""Add new parameter to Dog(correction)

Revision ID: cfdddab1af2f
Revises: 67807ba4460c
Create Date: 2024-11-29 16:44:58.174244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfdddab1af2f'
down_revision: Union[str, None] = '67807ba4460c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adopted_dogs', 'id_chip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('adoption_dogs', 'id_chip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('static_dogs', 'id_chip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('static_dogs', 'id_chip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('adoption_dogs', 'id_chip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('adopted_dogs', 'id_chip',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
