"""config adopted dog realtion

Revision ID: d92545ad4919
Revises: 592484ee664f
Create Date: 2024-11-28 10:28:19.162687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92545ad4919'
down_revision: Union[str, None] = '592484ee664f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_owner_direction', table_name='owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_owner_direction', 'owner', ['direction'], unique=False)
    # ### end Alembic commands ###
